### ISSUE TITLE
Show health of harvesters

### ISSUE THREAD

**Issue by grayfallstown** [grayfallstown/Chia-Plot-Status#82]
It is important to know if there are issues with the harvesters or all the plotting was for nothing.

Add a button to check Health of harvesters.

Show a text based summary and a Heatmap of lookup times per Harvester, as slow lookup times can make you miss out on a reward if you have the solution but your harvester cannot deliver in time.

**Comment by grayfallstown** [comment]
Most basic stats are in the current release. More coming

**Comment by grayfallstown** [comment]
## TODO

- [ ] Selectbox for summary time.
      Current commit summarizes the last 500 entries (about 90 minutes).
      Selectbox for 56 (10m), 333 (60min), 500 (90m), 1500 (3h), 7000 (12h), 8000 (day), 10080 (week), all

- [ ] Tab for each harvester
       Sub-tab showing heatmap over lookup time
       Sub-tab listing last n entries

- [ ] Refresh harvester dialog
       SummaryTime <= 60min refresh every minute
       SummaryTime > 60min refresh every ten minutes

- [ ] Caching mechanism for harvester logs.
       Don't reread debug.log2, debug.log3, etc if they did not change.
       Don't use TailLineEmitter to stay updated: it keeps the log file open and could prevent chias log rotation.
       Persist cache of debug.log2 and the others and clean up/update the cache when log rotation happend
